baseURL: https://blog.jiang.news/
languageCode: en-us

# 使用主题
theme: PaperMod

# 设置站标题
title: Jiang.news
params: &params_a
  # 设置站标题前logo，[dark, light]
  label:
    icon: XIAOZHOU/xiaozhou-1c/xiaozhou.png
  
  # favicon
  assets:
      favicon: "https://baidu.com/XIAOZHOU/xiaozhou-1c/favicon.ico"
      favicon16x16:  "https://baidu.com/XIAOZHOU/xiaozhou-1c/favicon-16x16.png"
      favicon32x32:  "/XIAOZHOU/xiaozhou-1c/favicon-32x32.png"
      apple_touch_icon:  "/XIAOZHOU/xiaozhou-1c/apple-touch-icon.png"
      safari_pinned_tab:  "/XIAOZHOU/xiaozhou-1c/safari-pinned-tab.svg"

# 亮暗模式
params: &params_aa
  <<: *params_a
  # 设置用户是否可切换亮暗模式，boolen
  disableThemeToggle: true
  disableThemeToggle: false
  # 设置亮色或暗色模式，[dark, light]
  defaultTheme: light

# 搜索
params: &params_aaa
  <<: *params_aa
  fuseOpts:
      isCaseSensitive: false
      shouldSort: true
      location: 0
      distance: 1000
      threshold: 0.4
      minMatchCharLength: 0
      keys: ["title", "permalink", "summary", "content"]

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

params:
  <<: *params_aaa
  showBreadCrumbs: true
  showReadingTime: true
  showShareButtons: true
  showPostNavLinks: true
  ShowToc: true

  ShareButtons: ["telegram"]

  components: ["telegram"]



  homeInfoParams:
    enabled: true
    Title: Hi there !
    Content: Welcome to my blog ... 

  profileMode:
    enabled: true
    # enabled: false
    title: "<THIS IS Title>" # optional default will be site title
    subtitle: "Hi there, this is Jiang's self-reserved cropland."
    imageUrl: "XIAOZHOU/xiaozhou-1s/xiaozhou.png" # optional
    imageTitle: "This is called XIAOZHOW, the icon of mine." # optional
    imageWidth: 240 # custom size
    imageHeight: 240 # custom size
    buttons:
      - name: Archive
        url: "/archives"
      - name: Github
        url: "https://github.com/jiangqucheng"

  socialIcons: # optional
    - name: "github"
      url: "https://github.com/jiangqucheng"
    - name: "bilibili"
      url: "https://space.bilibili.com/10861680"
    - name: "facebook"
      url: "https://www.facebook.com/qucheng.jiang"
    - name: "email"
      url: "mailto://jiangquchengpeter@hotmail.com"


menu: 
  main: 
    - identifier: search
      name: Q
      url: /search/
      Description: sssss
      weight: -1
    - identifier: categories
      name: "<Categories>"
      url: /categories/
      Description: ssssssss
      weight: 1
    - identifier: "#tags"
      name: "#Tags"
      url: /tags/
      Description: sssssqqsss
      weight: 2
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 3
