baseURL: http://Moving.Jiang.News/
languageCode: en-us
env: production

# 使用主题
theme: PaperMod

# 设置站标题
title: Moving.Jiang.News
params: &params_a
  # 设置站标题前logo，[dark, light]
  label:
    icon: XIAOZHOU/xiaozhou-1c/xiaozhou.png
  
  # favicon
  assets:
      favicon: "/XIAOZHOU/xiaozhou-1c/favicon.ico"
      favicon16x16:  "/XIAOZHOU/xiaozhou-1c/favicon-16x16.png"
      favicon32x32:  "/XIAOZHOU/xiaozhou-1c/favicon-32x32.png"
      apple_touch_icon:  "/XIAOZHOU/xiaozhou-1c/apple-touch-icon.png"
      safari_pinned_tab:  "/XIAOZHOU/xiaozhou-1c/safari-pinned-tab.svg"

# 亮暗模式
params: &params_aa
  <<: *params_a
  # 设置用户是否可切换亮暗模式，boolen
  disableThemeToggle: true
  # disableThemeToggle: false
  # 设置亮色或暗色模式，[dark, light]
  defaultTheme: light

# 搜索
params: &params_aaa
  <<: *params_aa
  fuseOpts:
      isCaseSensitive: false
      shouldSort: true
      location: 0
      distance: 1000
      threshold: 0.4
      minMatchCharLength: 0
      keys: ["title", "permalink", "summary", "content"]

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

params:
  <<: *params_aaa
  showBreadCrumbs: true
  showReadingTime: true
  showShareButtons: true
  showPostNavLinks: true
  # ShowToc: true
  disableScrollToTop: true
  ShowToc: false

  production: true

  ShareButtons: ["telegram", "twitter", "facebook", "reddit", "whatsapp"]

  components: ["telegram", "twitter", "facebook", "reddit", "whatsapp"]

  homeInfoParams:
    enabled: true
    Title:  "Moving Sale \n
    
    搬家甩卖啦！"
    Content: "自提地址：160 Pleasant St. Malden, MA \n

    预定 8/23 截至，微信联系：jiangquchengpeter， \n
    
    链接在物件就在，均可议价  "

  # socialIcons: # optional
  #   - name: "email"
  #     url: "mailto://jiangqucheng@hotmail.com"

menu: 
  main: 
    - identifier: search
      name: 搜索
      url: /search/
      Description: 搜索想要的物件
      weight: -1
    - identifier: categories
      name: "<分类>"
      url: /categories/
      Description: 就几件东西有啥好分的
      weight: 1
    - identifier: tags
      name: "#标签"
      url: /tags/
      Description: 莫名其妙的功能
      weight: 2
